-- Seed organizations
INSERT INTO organizations (id, name, type, finess, siret, plan) VALUES
  ('11111111-1111-1111-1111-111111111111', 'CH Armentières', 'CH', '590780375', '26590078500016', 'pro'),
  ('22222222-2222-2222-2222-222222222222', 'EPSM Lille Métropole', 'EPSM', '590014193', '26590001400021', 'pro'),
  ('33333333-3333-3333-3333-333333333333', 'EHPAD Les Tilleuls', 'EHPAD', '590790366', '26590079000019', 'free'),
  ('44444444-4444-4444-4444-444444444444', 'CH Roubaix', 'CH', '590000396', '26590000300012', 'enterprise'),
  ('55555555-5555-5555-5555-555555555555', 'Numih France', 'EDITEUR', NULL, '81234567800015', 'enterprise');

-- Seed knowledge base
INSERT INTO knowledge_base (error_code, title, description, cause, fix, format, occurrences, is_public) VALUES
  ('RSU_52003', 'Répertoire de dépôt manquant', 'Le répertoire FTP cible n''existe pas ou les droits sont insuffisants', 'Configuration Enovacom incorrecte ou répertoire supprimé côté serveur', 'Vérifier la configuration FTP dans Enovacom. Contacter l'''équipe TDT pour recréer le répertoire et vérifier les permissions.', 'PESV2', 47, true),
  ('UTF8_DOUBLE_ENCODE', 'Double encodage UTF-8 sur les accents', 'Les caractères accentués (é, è, à...) sont encodés deux fois, corrompant la signature XAdES', 'Erreur de chaîne de traitement dans le middleware — le fichier est converti en UTF-8 alors qu''il l''est déjà', 'Vérifier l''option "force UTF-8 reconversion" dans le connecteur Enovacom. Désactiver si le fichier source est déjà en UTF-8.', 'PESV2', 23, true),
  ('74002', 'Connexion FTP refusée', 'Le serveur FTP cible refuse la connexion (code 74002)', 'Firewall, IP non autorisée, ou service FTP arrêté côté DGFiP/AIFE', 'Vérifier que l''IP de l''établissement est whitelistee. Tester la connectivité réseau. Contacter le support DGFiP si persistant.', 'PESV2', 31, true),
  ('74003', 'Timeout connexion FTP', 'La connexion FTP expire avant établissement (code 74003)', 'Latence réseau excessive ou problème de routage vers le serveur cible', 'Augmenter le timeout dans la configuration Enovacom. Vérifier la QoS réseau. Planifier les envois hors pics de charge.', 'PESV2', 18, true),
  ('74178', 'Répertoire FTP inaccessible', 'Le répertoire FTP existe mais est inaccessible (code 74178)', 'Droits insuffisants sur le répertoire ou montage NFS défaillant côté serveur', 'Vérifier les droits UNIX sur le répertoire distant. Contacter l''administrateur du serveur de collecte.', 'PESV2', 12, true),
  ('SIRET_INVALIDE', 'SIRET fournisseur invalide', 'Le numéro SIRET du fournisseur ne passe pas la validation Luhn', 'Erreur de saisie ou SIRET de l''établissement non encore actif dans CHORUS Pro', 'Vérifier le SIRET dans le registre SIRENE. S''assurer que le fournisseur est référencé dans CHORUS Pro avec le bon SIRET.', 'CHORUS_UBL', 29, true),
  ('MONTANT_INCOHERENT', 'Incohérence des montants HT/TVA/TTC', 'Le total TTC ne correspond pas à la somme HT + TVA avec la tolérance admise (0.02€)', 'Arrondi incorrect dans le logiciel de facturation', 'Recalculer les montants avec 2 décimales exactes. Vérifier le paramétrage d''arrondi du logiciel.', 'CHORUS_UBL', 15, true),
  ('BLOC_BUDGETAIRE_MANQUANT', 'BlocBudgétaire absent', 'L'''élément XML <BlocBudgétaire> est absent ou vide dans le flux PES V2', 'Paramétrage incomplet dans le logiciel financier (Hélios ou progiciel tiers)', 'Compléter le paramétrage de l''imputation budgétaire. Vérifier les codes nature/fonction.', 'PESV2', 34, true),
  ('XSD_NON_CONFORME', 'Fichier non conforme au schéma XSD', 'La validation XSD du fichier PES V2 échoue — un ou plusieurs éléments obligatoires sont absents ou mal formés', 'Version XSD incorrecte ou mise à jour du schéma non intégrée dans le logiciel', 'Mettre à jour le schéma XSD dans le logiciel. Utiliser la version officielle DGFiP disponible sur Hélios.', 'PESV2', 41, true),
  ('NON_ACQUITTE', 'Flux en statut Non_Acquitté', 'Le flux transmis n''a pas été acquitté par Hélios dans le délai attendu', 'Problème de traitement côté DGFiP ou flux bloqué dans la file d''attente', 'Vérifier le statut dans UseItFlow. Contacter la DGFiP si le flux reste en attente plus de 48h ouvées.', 'PESV2', 22, true),
  ('NAF_INVALIDE', 'Code NAF/APE invalide', 'Le code NAF fourni n''existe pas dans la nomenclature en vigueur', 'Code NAF obsolete ou non renseigné dans le référentiel fournisseur', 'Vérifier le code NAF de l''établissement sur l''INSEE. Mettre à jour le référentiel CHORUS Pro.', 'CHORUS_UBL', 8, true),
  ('CERT_EXPIRE', 'Certificat de signature expiré', 'Le certificat utilisé pour signer les flux XAdES PES V2 a expiré', 'Renouvellement du certificat oublié ou procédure non déclenchée', 'Renouveler le certificat auprès de l''AC agréée. Mettre à jour dans Enovacom. Délai : agir sous 48h pour éviter le blocage complet.', 'PESV2', 6, true),
  ('STRUCTURE_CSV_INVALIDE', 'Structure CSV non conforme', 'Le fichier CSV ne respecte pas la structure attendue (séparateur, en-têtes, nombre de colonnes)', 'Export paramétré avec un séparateur différent (virgule vs point-virgule) ou colonnes manquantes', 'Vérifier le paramétrage d''export : séparateur point-virgule, encodage UTF-8 sans BOM, guillemets sur les champs texte.', 'CSV', 11, true),
  ('REJET_APPLICATIF_CHORUS', 'Rejet applicatif CHORUS Pro', 'CHORUS Pro a rejeté la facture pour motif applicatif (données métier invalides)', 'Données fournisseur incorrectes, montants hors tolérance, ou référence de commande inconnue', 'Analyser le code de rejet dans le portail CHORUS Pro. Corriger les données et soumettre à nouveau.', 'CHORUS_UBL', 19, true),
  ('TIMEOUT_HELIOS', 'Timeout Hélios', 'La connexion vers Hélios expire pendant l''envoi du flux PES V2', 'Indisponibilité temporaire Hélios ou fichier trop volumineux', 'Attendre 30 minutes et relancer. Si persistant, découper le flux en lots plus petits (< 5000 lignes).', 'PESV2', 9, true);
